# Generated by Django 5.1 on 2024-08-26 22:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlName', models.CharField(max_length=100, unique=True, verbose_name='Nazwa url')),
                ('title', models.CharField(max_length=200, verbose_name='Nagłówek')),
                ('description', models.TextField(verbose_name='Opis strony')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
            },
        ),
    ]
